
platform :ios, '10.0'

use_frameworks!

target 'GitHub' do

  # Pods for GitHub
  
  pod 'Alamofire'
  pod 'SnapKit'

  target 'GitHubTests' do
    inherit! :search_paths
    
  end

  target 'GitHubUITests' do
    inherit! :search_paths
    
  end

end
